FROM alpine

ARG TARGETPLATFORM
ARG VERSION=Release33

RUN apk --no-cache add curl

RUN curl -sSL https://apix.vercel.app/github/pymumu/smartdns/%5esmartdns.*.x86_64-linux-all.tar.gz -o smartdns.tar.gz \
  && tar zxvf smartdns.tar.gz \
  && mv smartdns/usr/sbin/smartdns /bin/smartdns \
  && chmod +x /bin/smartdns \
  && rm -rf smartdns*

ADD overture/smartdns-start.sh /start.sh
ADD overture/smartdns.conf /config.conf

run chmod +x /start.sh

WORKDIR /

VOLUME ["/smartdns"]

EXPOSE 53535

CMD ["/start.sh"]